name: Unfunny
favicon: null
layout_spectrum: 0.25542
typography_spectrum: 0.29811
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4ede9'
    - '#299484'
    - '#efd701'
    - '#ea5885'
    - '#000000'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
