name: Unfunny
favicon: null
layout_spectrum: 0.8808344032149762
typography_spectrum: 0.493236648151651
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4ede9'
    - '#299484'
    - '#efd701'
    - '#ea5885'
    - '#000000'
  brandStrength: 0.875
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
