name: Unfunny Valentine
favicon: null
layout_spectrum: 0.49339
typography_spectrum: 0.29977
title: Unfunny Valentine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4ede9'
    - '#299484'
    - '#efd701'
    - '#ea5885'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
