name: Unfunny
favicon: null
layout_spectrum: 0.8808344032149762
typography_spectrum: 0.493236648151651
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9478111222852021
  lightness: 0.2811196756083518
  saturation: 0.03610895969904959
  rhythmicContrast: 0.7756299385800958
purpose: []
